### ISSUE TITLE
The type initializer for 'SIPSorcery.SIP.SIPDns' threw an exception in 'SIPRegistrationUserAgent' on Android

### ISSUE THREAD

**Issue by neminush** [sipsorcery/sipsorcery#325]
This line throws an exception with message "The type initializer for 'SIPSorcery.SIP.SIPDns' threw an exception" on Android:
![SIPSorcery SIP SIPDns](https://user-images.githubusercontent.com/33318899/95686685-1e25d680-0c08-11eb-82d7-cf13216023cb.png)

SIPRegistrationUserAgent -> SendInitialRegister() -> ResolveSIPUriAsync(...)

There is no way to replace 'ResolveSIPUriAsync' method :(
'SIPTransport' does not implement the 'ISIPTransport' interface to be loosely related to 'SIPRegistrationUserAgent'. And this method isn't even virtual.

'SIPDns.ResolveAsync' is static and immutable :(

**Comment by neminush** [comment]
In iOS this line works fine. In Android it throws an exception. The field 'm_registrarHost' contains '5.188.43.170:5060' string when it happens.

**Comment by sipsorcery** [comment]
Does the same error happen in the Visual Studio Android emulator? That's currently the only Android option I've got to test with.

Are you using a Xamarin Forms app? If you can provide a minimal example that can help a lot. Even it's just a zip file of your test app.

**Comment by neminush** [comment]
I haven't checked in any emulator yet, only checked on the device (Huawei).

I don't use Xamarin.Forms.

I'll gather more information later. I'll check it on other devices.

I'm a little busy right now. I'm trying to figure out why 'SIPRegistrationUserAgent' in SIPSorcery 3.6.0 works fine on mobile devices using UDP, but it don't work in SIPSorcery 4.0.82-pre.

At the same time, 'SIPRegistrationUserAgent' works perfectly in the .NET Core console application in SIPSorcery 4.0.82-pre.

In mobile devices (Android & iOS) I get a timeout from 'SIPRegistrationUserAgent' in SIPSorcery 4.0.82-pre using UDP.

With TCP works fine, but it doesn't suit me.

**Comment by neminush** [comment]
I have checked on Genymotion emulator - the bug doesn't show up. Registration works fine. I'll check more on other devices and emulators later.

**Comment by neminush** [comment]
This is a test Android project for research.
[SIPSorceryAndroidTest.zip](https://github.com/sipsorcery/sipsorcery/files/5372957/SIPSorceryAndroidTest.zip)

**Comment by sipsorcery** [comment]
Thanks for the example. I've used it to track down the cause of the original DNS exception and it's the one I expected.

`Error resolving name servers (Object reference not set to an instance of an object.) (Could not find file "/etc/resolv.conf") ---> System.NullReferenceException: Object reference not set to an instance of an object.`

It's related to https://github.com/MichaCo/DnsClient.NET/issues/17.

There should be a workaround where the DNS servers can be set explicitly and thus avoid the need for `resolv.conf`. I'll track that down.

**Comment by sipsorcery** [comment]
Can confirm setting the DNS servers explicitly fixes this exception. In `SIPDns` changed the `LookupClient` initialisation to:

```
static SIPDns()
{
	LookupClientOptions clientOptions = new LookupClientOptions(DnsClient.NameServer.GooglePublicDns)
	{
		Retries = DNS_RETRIES_PER_SERVER,
		Timeout = TimeSpan.FromSeconds(DNS_TIMEOUT_SECONDS),
		UseCache = true,
		// TODO: Re-enable when DnsClient adds cache querying.
		//UseCacheForFailures = true,
	};

	_lookupClient = new LookupClient(clientOptions);
}
```

The exception is no longer thrown and the Debug Output eventually returns:

```
[0:]  =-*-==-*-=> registration temporary failure
uri: sip:123456789@5.188.43.170:5060;
Registration transaction to 5.188.43.170:5060 for sip:123456789@5.188.43.170:5060 timed out.
```

For a permanent fix I need to think of a way to elegantly deal with the `DnsClient` library not being able to access the system DNS entries. Ideally system entries should be used if available and only as a last resort fallback to known public servers.
